// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $admin_admin_dashboard from "./routes/admin/admin/dashboard.tsx";
import * as $admin_admin_inventory from "./routes/admin/admin/inventory.tsx";
import * as $admin_admin_inventory_add from "./routes/admin/admin/inventory/add.tsx";
import * as $admin_login from "./routes/admin/login.tsx";
import * as $auth_login from "./routes/auth/login.tsx";
import * as $auth_register from "./routes/auth/register.tsx";
import * as $guest from "./routes/guest.tsx";
import * as $index from "./routes/index.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $perfil_id_ from "./routes/perfil/[id].tsx";
import * as $perfil_id_editar from "./routes/perfil/[id]/editar.tsx";
import * as $perfil_id_reservar from "./routes/perfil/[id]/reservar.tsx";
import * as $registro_completado from "./routes/registro-completado.tsx";
import * as $reserva_id_ from "./routes/reserva/[id].tsx";
import * as $sesion from "./routes/sesion.tsx";
import * as $admincitas from "./islands/admincitas.tsx";
import * as $info from "./islands/info.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/admin/admin/dashboard.tsx": $admin_admin_dashboard,
    "./routes/admin/admin/inventory.tsx": $admin_admin_inventory,
    "./routes/admin/admin/inventory/add.tsx": $admin_admin_inventory_add,
    "./routes/admin/login.tsx": $admin_login,
    "./routes/auth/login.tsx": $auth_login,
    "./routes/auth/register.tsx": $auth_register,
    "./routes/guest.tsx": $guest,
    "./routes/index.tsx": $index,
    "./routes/logout.tsx": $logout,
    "./routes/perfil/[id].tsx": $perfil_id_,
    "./routes/perfil/[id]/editar.tsx": $perfil_id_editar,
    "./routes/perfil/[id]/reservar.tsx": $perfil_id_reservar,
    "./routes/registro-completado.tsx": $registro_completado,
    "./routes/reserva/[id].tsx": $reserva_id_,
    "./routes/sesion.tsx": $sesion,
  },
  islands: {
    "./islands/admincitas.tsx": $admincitas,
    "./islands/info.tsx": $info,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
